name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Tested with dotnet
      run: dotnet test --configuration Release
